name: docs_generation_workflow

# Execute automatically when pushed to main
on:
  push:
    branches:
      - main

jobs:
  generate_docs:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.13"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install numpy sphinx sphinx-book-theme 
          
      - name: Install dependencies for exshalos
        run: |
          apt install -u -y libfftw3-dev libgsl-dev libgslcblas0 libomp-dev

      - name: Install exshalos
        run: |
          pip install -e .

      - name: Build documentation
        run: sphinx-build -b html ./docs ./docs/build/html

      - name: Deploy to GitHub Pages 
        uses: peaceiris/actions-gh-pages@v3
        with: 
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs/build/html
          branch: gh-pages
